import { CategoryType, ProductType } from "./types";

export const CATEGORIES_DATA: Omit<CategoryType, "products">[] = [
  {
    id: "cat-ai-prod",
    name: "AI & Productivity Tools",
    slug: "ai-productivity",
    icon: "Bot",
    description: "Tingkatkan produktivitas kerja, belajar, riset & desain dengan AI cerdas premium!",
    order: 1,
  },
  {
    id: "cat-streaming",
    name: "Streaming Apps",
    slug: "streaming-apps",
    icon: "Tv",
    description: "Nonton film, serial, drakor, anime & mini drama favorit tanpa jeda iklan!",
    order: 2,
  },
];

export const PRODUCTS_DATA: (Omit<ProductType, "category"> & { categorySlug: string })[] = [
  // ==========================================
  // AI & PRODUCTIVITY (18 APPS)
  // ==========================================
  {
    id: "prod-claude",
    name: "Claude AI Pro",
    slug: "claude-pro",
    categoryId: "cat-ai-prod",
    categorySlug: "ai-productivity",
    description: "Akses Claude 3.5 Sonnet & Opus untuk coding, riset, dan analisis teks super akurat.",
    features: ["Claude 3.5 Sonnet & Opus", "Artifacts Mode & Coding", "5x Usage Limit", "Garansi Full Sesuai Durasi"],
    icon: "Sparkles",
    badge: "🔥 Best Seller",
    badgeColor: "pink",
    isPopular: true,
    warrantyDays: 30,
    order: 1,
    variants: [
      { id: "v-claude-1m-sh", productId: "prod-claude", duration: "1 Bulan", accountType: "Sharing Hemat", price: 65000, originalPrice: 120000, isDefault: true },
      { id: "v-claude-1m-pr", productId: "prod-claude", duration: "1 Bulan", accountType: "Private Akun", price: 295000, originalPrice: 350000, isDefault: false },
      { id: "v-claude-3m-sh", productId: "prod-claude", duration: "3 Bulan", accountType: "Sharing Hemat", price: 180000, originalPrice: 340000, isDefault: false },
    ],
  },
  {
    id: "prod-chatgpt-plus",
    name: "ChatGPT Plus (GPT-4o)",
    slug: "chatgpt-plus",
    categoryId: "cat-ai-prod",
    categorySlug: "ai-productivity",
    description: "Akses model GPT-4o, o1-preview, DALL-E 3, Voice Mode, dan Custom GPTs terlengkap.",
    features: ["Model GPT-4o & GPT-o1", "DALL-E 3 Image Creator", "Advanced Data Analysis", "Garansi Anti-Revoke"],
    icon: "BrainCircuit",
    badge: "⭐ Top Choice",
    badgeColor: "blue",
    isPopular: true,
    warrantyDays: 30,
    order: 2,
    variants: [
      { id: "v-gpt-1m-sh", productId: "prod-chatgpt-plus", duration: "1 Bulan", accountType: "Sharing", price: 50000, originalPrice: 110000, isDefault: true },
      { id: "v-gpt-1m-pr", productId: "prod-chatgpt-plus", duration: "1 Bulan", accountType: "Private", price: 290000, originalPrice: 340000, isDefault: false },
      { id: "v-gpt-3m-sh", productId: "prod-chatgpt-plus", duration: "3 Bulan", accountType: "Sharing", price: 140000, originalPrice: 280000, isDefault: false },
      { id: "v-gpt-1y-pr", productId: "prod-chatgpt-plus", duration: "1 Tahun", accountType: "Private", price: 1150000, originalPrice: 2400000, isDefault: false },
    ],
  },
  {
    id: "prod-chatgpt-go",
    name: "ChatGPT Go / Edu Plan",
    slug: "chatgpt-go",
    categoryId: "cat-ai-prod",
    categorySlug: "ai-productivity",
    description: "Paket ekonomis ChatGPT untuk pelajar, mahasiswa & pekerja kreatif.",
    features: ["Akses GPT-4o Standar", "Unlimited Chat Fast", "Stabil & Ramah Kantong", "Garansi Replace"],
    icon: "Zap",
    badge: "💸 Termurah",
    badgeColor: "yellow",
    isPopular: false,
    warrantyDays: 30,
    order: 3,
    variants: [
      { id: "v-gptgo-1m", productId: "prod-chatgpt-go", duration: "1 Bulan", accountType: "Sharing", price: 25000, originalPrice: 50000, isDefault: true },
      { id: "v-gptgo-3m", productId: "prod-chatgpt-go", duration: "3 Bulan", accountType: "Sharing", price: 65000, originalPrice: 120000, isDefault: false },
      { id: "v-gptgo-6m", productId: "prod-chatgpt-go", duration: "6 Bulan", accountType: "Sharing", price: 115000, originalPrice: 220000, isDefault: false },
    ],
  },
  {
    id: "prod-gemini",
    name: "Gemini Advanced Ultra",
    slug: "gemini-advanced",
    categoryId: "cat-ai-prod",
    categorySlug: "ai-productivity",
    description: "AI Google dengan 2M context window, integrasi Google Workspace & 2TB Cloud Storage.",
    features: ["Model 1.5 Pro 2M Token", "Integrasi Docs, Gmail, Drive", "Bonus 2TB Google One", "Full Garansi"],
    icon: "Boxes",
    badge: "☁️ 2TB Cloud",
    badgeColor: "lilac",
    isPopular: true,
    warrantyDays: 30,
    order: 4,
    variants: [
      { id: "v-gem-1m-pr", productId: "prod-gemini", duration: "1 Bulan", accountType: "Private Email Anda", price: 45000, originalPrice: 125000, isDefault: true },
      { id: "v-gem-3m-pr", productId: "prod-gemini", duration: "3 Bulan", accountType: "Private Email Anda", price: 120000, originalPrice: 300000, isDefault: false },
      { id: "v-gem-1y-pr", productId: "prod-gemini", duration: "1 Tahun", accountType: "Private", price: 390000, originalPrice: 900000, isDefault: false },
    ],
  },
  {
    id: "prod-ms365",
    name: "Microsoft 365 + 1TB OneDrive",
    slug: "microsoft-365",
    categoryId: "cat-ai-prod",
    categorySlug: "ai-productivity",
    description: "Word, Excel, PowerPoint, Outlook & 1TB Cloud Storage OneDrive resmi & aman.",
    features: ["1TB Cloud OneDrive", "Word, Excel, PowerPoint", "Install hingga 5 Device", "Garansi 1 Tahun"],
    icon: "LayoutGrid",
    badge: "💼 Kantor & Skripsi",
    badgeColor: "mint",
    isPopular: true,
    warrantyDays: 365,
    order: 5,
    variants: [
      { id: "v-ms-1y-pr", productId: "prod-ms365", duration: "1 Tahun", accountType: "Private Akun Sendiri", price: 75000, originalPrice: 250000, isDefault: true },
      { id: "v-ms-lifetime", productId: "prod-ms365", duration: "Lifetime", accountType: "Custom Domain", price: 125000, originalPrice: 400000, isDefault: false },
    ],
  },
  {
    id: "prod-perplexity",
    name: "Perplexity Pro AI",
    slug: "perplexity-pro",
    categoryId: "cat-ai-prod",
    categorySlug: "ai-productivity",
    description: "Mesin pencari AI mutakhir dengan sitasi sumber lengkap, Claude 3.5 & GPT-4o switcher.",
    features: ["Pilih Model GPT-4o / Claude", "Unlimited Pro Search", "File & PDF Analysis", "Garansi Aktif"],
    icon: "Compass",
    badge: "🔍 Riset Ilmiah",
    badgeColor: "blue",
    isPopular: true,
    warrantyDays: 30,
    order: 6,
    variants: [
      { id: "v-perp-1m-sh", productId: "prod-perplexity", duration: "1 Bulan", accountType: "Sharing", price: 35000, originalPrice: 90000, isDefault: true },
      { id: "v-perp-1m-pr", productId: "prod-perplexity", duration: "1 Bulan", accountType: "Private", price: 75000, originalPrice: 200000, isDefault: false },
      { id: "v-perp-1y-pr", productId: "prod-perplexity", duration: "1 Tahun", accountType: "Private", price: 350000, originalPrice: 850000, isDefault: false },
    ],
  },
  {
    id: "prod-coursera",
    name: "Coursera Plus",
    slug: "coursera-plus",
    categoryId: "cat-ai-prod",
    categorySlug: "ai-productivity",
    description: "Akses ribuan sertifikasi resmi dari Google, IBM, Stanford, dan universitas ternama dunia.",
    features: ["Akses 7000+ Kursus & Sertifikat", "Universitas & Tech Top Dunia", "Sertifikat Bernama Asli", "Garansi Full"],
    icon: "GraduationCap",
    badge: "🎓 Sertifikat Karir",
    badgeColor: "pink",
    isPopular: false,
    warrantyDays: 30,
    order: 7,
    variants: [
      { id: "v-coursera-1m", productId: "prod-coursera", duration: "1 Bulan", accountType: "Private Email", price: 120000, originalPrice: 400000, isDefault: true },
      { id: "v-coursera-3m", productId: "prod-coursera", duration: "3 Bulan", accountType: "Private Email", price: 290000, originalPrice: 900000, isDefault: false },
      { id: "v-coursera-1y", productId: "prod-coursera", duration: "1 Tahun", accountType: "Private Email", price: 650000, originalPrice: 2000000, isDefault: false },
    ],
  },
  {
    id: "prod-duolingo",
    name: "Duolingo Super / Max",
    slug: "duolingo-super",
    categoryId: "cat-ai-prod",
    categorySlug: "ai-productivity",
    description: "Belajar bahasa asing tanpa batas hati, bebas iklan, dan review kesalahan otomatis.",
    features: ["Unlimited Hearts ❤️", "No Ads / Bebas Iklan", "Fitur Mistake Review", "Via Invite Family Aman"],
    icon: "Languages",
    badge: "🦉 Belajar Bahasa",
    badgeColor: "mint",
    isPopular: true,
    warrantyDays: 365,
    order: 8,
    variants: [
      { id: "v-duo-1y", productId: "prod-duolingo", duration: "1 Tahun", accountType: "Private Invite", price: 45000, originalPrice: 150000, isDefault: true },
      { id: "v-duo-6m", productId: "prod-duolingo", duration: "6 Bulan", accountType: "Private Invite", price: 28000, originalPrice: 90000, isDefault: false },
    ],
  },
  {
    id: "prod-zoom",
    name: "Zoom Pro Meeting",
    slug: "zoom-pro",
    categoryId: "cat-ai-prod",
    categorySlug: "ai-productivity",
    description: "Meeting online tanpa batas 40 menit, kapasitas 100/300 peserta, cloud recording & live stream.",
    features: ["Unlimited 30 Jam / Meeting", "100-300 Peserta", "Co-Host & Breakout Room", "Full Support"],
    icon: "Video",
    badge: "📹 Meeting HD",
    badgeColor: "blue",
    isPopular: false,
    warrantyDays: 30,
    order: 9,
    variants: [
      { id: "v-zoom-1d", productId: "prod-zoom", duration: "1 Hari / 24 Jam", accountType: "Host Ready", price: 15000, originalPrice: 35000, isDefault: false },
      { id: "v-zoom-1m", productId: "prod-zoom", duration: "1 Bulan", accountType: "Private Email", price: 65000, originalPrice: 180000, isDefault: true },
    ],
  },
  {
    id: "prod-quillbot",
    name: "Quillbot Premium",
    slug: "quillbot-premium",
    categoryId: "cat-ai-prod",
    categorySlug: "ai-productivity",
    description: "Paraphrase teks tanpa batas kata, bypass AI detection, dan grammar checker terlengkap.",
    features: ["Unlimited Words Paraphrase", "Semua Modes (Formal, Creative, Simple)", "Plagiarism Checker 25k words", "Garansi Anti-Hold"],
    icon: "Feather",
    badge: "📝 Anti Plagiasi",
    badgeColor: "yellow",
    isPopular: true,
    warrantyDays: 30,
    order: 10,
    variants: [
      { id: "v-quill-1m-sh", productId: "prod-quillbot", duration: "1 Bulan", accountType: "Sharing", price: 25000, originalPrice: 60000, isDefault: true },
      { id: "v-quill-3m-sh", productId: "prod-quillbot", duration: "3 Bulan", accountType: "Sharing", price: 55000, originalPrice: 140000, isDefault: false },
      { id: "v-quill-1y-pr", productId: "prod-quillbot", duration: "1 Tahun", accountType: "Private", price: 210000, originalPrice: 500000, isDefault: false },
    ],
  },
  {
    id: "prod-kiro-ai",
    name: "Kiro AI Pro",
    slug: "kiro-ai",
    categoryId: "cat-ai-prod",
    categorySlug: "ai-productivity",
    description: "Asisten AI serbaguna untuk pembuatan konten, riset data otomatis, dan generator prompt.",
    features: ["Multi-Model AI Engine", "Content Generator Kilat", "Template Siap Pakai", "Full Garansi"],
    icon: "Bot",
    badge: "⚡ AI New Gen",
    badgeColor: "lilac",
    isPopular: false,
    warrantyDays: 30,
    order: 11,
    variants: [
      { id: "v-kiro-1m", productId: "prod-kiro-ai", duration: "1 Bulan", accountType: "Private", price: 40000, originalPrice: 100000, isDefault: true },
      { id: "v-kiro-3m", productId: "prod-kiro-ai", duration: "3 Bulan", accountType: "Private", price: 95000, originalPrice: 240000, isDefault: false },
    ],
  },
  {
    id: "prod-jenni-ai",
    name: "Jenni AI Academic Writer",
    slug: "jenni-ai",
    categoryId: "cat-ai-prod",
    categorySlug: "ai-productivity",
    description: "Sahabat mahasiswa & dosen untuk menulis skripsi, tesis, paper jurnal dengan sitasi otomatis.",
    features: ["Auto-Citation (APA, IEEE, Harvard)", "AI Autocomplete Paper", "Research Library Integration", "Garansi Penuh"],
    icon: "BookOpen",
    badge: "📚 Spesialis Skripsi",
    badgeColor: "pink",
    isPopular: true,
    warrantyDays: 30,
    order: 12,
    variants: [
      { id: "v-jenni-1m-sh", productId: "prod-jenni-ai", duration: "1 Bulan", accountType: "Sharing", price: 38000, originalPrice: 90000, isDefault: true },
      { id: "v-jenni-1m-pr", productId: "prod-jenni-ai", duration: "1 Bulan", accountType: "Private", price: 85000, originalPrice: 190000, isDefault: false },
    ],
  },
  {
    id: "prod-linkedin",
    name: "LinkedIn Premium Business / Career",
    slug: "linkedin-premium",
    categoryId: "cat-ai-prod",
    categorySlug: "ai-productivity",
    description: "Tingkatkan personal branding, kirim InMail langsung ke HRD recruiter, dan akses LinkedIn Learning.",
    features: ["InMail Credits ke HRD", "Who Viewed Your Profile", "Akses 16.000+ LinkedIn Learning", "Aktif via Link Resmi"],
    icon: "Briefcase",
    badge: "🎯 Karir Impian",
    badgeColor: "blue",
    isPopular: true,
    warrantyDays: 60,
    order: 13,
    variants: [
      { id: "v-li-1m", productId: "prod-linkedin", duration: "1 Bulan", accountType: "Private Redeem", price: 85000, originalPrice: 350000, isDefault: false },
      { id: "v-li-6m", productId: "prod-linkedin", duration: "6 Bulan", accountType: "Private Business", price: 290000, originalPrice: 950000, isDefault: true },
    ],
  },
  {
    id: "prod-wps",
    name: "WPS Office Pro",
    slug: "wps-office",
    categoryId: "cat-ai-prod",
    categorySlug: "ai-productivity",
    description: "Alternatif office ringan dengan fitur edit PDF lengkap, konversi dokumen & tanpa iklan.",
    features: ["Edit & Convert PDF to Word", "Cloud Storage 20GB", "No Ads & Bebas Watermark", "Multi-Device Sync"],
    icon: "FileSpreadsheet",
    badge: "📄 PDF Editor",
    badgeColor: "yellow",
    isPopular: false,
    warrantyDays: 365,
    order: 14,
    variants: [
      { id: "v-wps-1y", productId: "prod-wps", duration: "1 Tahun", accountType: "Private Akun", price: 50000, originalPrice: 150000, isDefault: true },
    ],
  },
  {
    id: "prod-grok",
    name: "Grok 2 AI (X Premium+)",
    slug: "grok-ai",
    categoryId: "cat-ai-prod",
    categorySlug: "ai-productivity",
    description: "AI paling jujur & real-time dengan akses database X / Twitter dan generator gambar FLUX.",
    features: ["Grok 2 & Grok 2 mini", "Image Generation FLUX AI", "Real-Time X Insights", "Garansi Sesuai Durasi"],
    icon: "Atom",
    badge: "🤖 Real-Time Data",
    badgeColor: "lilac",
    isPopular: false,
    warrantyDays: 30,
    order: 15,
    variants: [
      { id: "v-grok-1m-sh", productId: "prod-grok", duration: "1 Bulan", accountType: "Sharing", price: 55000, originalPrice: 130000, isDefault: true },
      { id: "v-grok-1m-pr", productId: "prod-grok", duration: "1 Bulan", accountType: "Private", price: 210000, originalPrice: 380000, isDefault: false },
    ],
  },
  {
    id: "prod-grammarly",
    name: "Grammarly Premium",
    slug: "grammarly-premium",
    categoryId: "cat-ai-prod",
    categorySlug: "ai-productivity",
    description: "Koreksi grammar, tone detector, vocabulary suggestion & plagiarism checker bahasa Inggris.",
    features: ["Advanced Grammar & Clarity", "Plagiarism Checker", "Tone & Confidence Detector", "Bisa Plugin Word & Chrome"],
    icon: "CheckCheck",
    badge: "✨ Grammar 100%",
    badgeColor: "mint",
    isPopular: true,
    warrantyDays: 30,
    order: 16,
    variants: [
      { id: "v-gram-1m-sh", productId: "prod-grammarly", duration: "1 Bulan", accountType: "Sharing", price: 25000, originalPrice: 70000, isDefault: true },
      { id: "v-gram-1m-pr", productId: "prod-grammarly", duration: "1 Bulan", accountType: "Private", price: 80000, originalPrice: 200000, isDefault: false },
      { id: "v-gram-1y-sh", productId: "prod-grammarly", duration: "1 Tahun", accountType: "Sharing", price: 150000, originalPrice: 400000, isDefault: false },
    ],
  },
  {
    id: "prod-deepl",
    name: "DeepL Pro Translator",
    slug: "deepl-pro",
    categoryId: "cat-ai-prod",
    categorySlug: "ai-productivity",
    description: "Penerjemah bahasa terbaik dunia dengan tata bahasa paling natural & profesional.",
    features: ["Terjemahan Dokumen PDF/Docx", "Formality Tone Custom", "Unlimited Text Translation", "Garansi Aktif"],
    icon: "Globe",
    badge: "🌐 Natural Translation",
    badgeColor: "blue",
    isPopular: false,
    warrantyDays: 30,
    order: 17,
    variants: [
      { id: "v-deepl-1m-sh", productId: "prod-deepl", duration: "1 Bulan", accountType: "Sharing", price: 35000, originalPrice: 85000, isDefault: true },
      { id: "v-deepl-1m-pr", productId: "prod-deepl", duration: "1 Bulan", accountType: "Private", price: 110000, originalPrice: 250000, isDefault: false },
    ],
  },
  {
    id: "prod-scribd",
    name: "Scribd / Everand Unlimited",
    slug: "scribd-unlimited",
    categoryId: "cat-ai-prod",
    categorySlug: "ai-productivity",
    description: "Akses jutaan ebook, audiobook, dokumen kuliah, slide materi, dan artikel ilmiah.",
    features: ["Download Ebook & Dokumen", "Audiobook Unlimited", "Bisa HP, Tablet & Web", "Garansi Full Replace"],
    icon: "BookMarked",
    badge: "📖 Jutaan Buku",
    badgeColor: "pink",
    isPopular: false,
    warrantyDays: 30,
    order: 18,
    variants: [
      { id: "v-scribd-1m-sh", productId: "prod-scribd", duration: "1 Bulan", accountType: "Sharing", price: 20000, originalPrice: 45000, isDefault: true },
      { id: "v-scribd-2m-pr", productId: "prod-scribd", duration: "2 Bulan", accountType: "Private", price: 45000, originalPrice: 90000, isDefault: false },
    ],
  },

  // ==========================================
  // STREAMING APPS (31 APPS)
  // ==========================================
  {
    id: "prod-netflix",
    name: "Netflix Premium 4K UHD",
    slug: "netflix-premium",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Kualitas 4K HDR Ultra HD, audio Dolby Atmos, profil ber-PIN dan anti-screen limit.",
    features: ["Kualitas 4K Ultra HD & HDR", "Pin Profile Pribadi", "Bisa Smart TV, HP, Laptop", "Garansi Anti-On Hold"],
    icon: "Film",
    badge: "🔥 Terlaris #1",
    badgeColor: "pink",
    isPopular: true,
    warrantyDays: 30,
    order: 101,
    variants: [
      { id: "v-nf-1m-1p", productId: "prod-netflix", duration: "1 Bulan", accountType: "1 Profil Private (PIN)", price: 28000, originalPrice: 54000, isDefault: true },
      { id: "v-nf-1m-full", productId: "prod-netflix", duration: "1 Bulan", accountType: "Private Full Akun 5 Profil", price: 145000, originalPrice: 186000, isDefault: false },
      { id: "v-nf-3m-1p", productId: "prod-netflix", duration: "3 Bulan", accountType: "1 Profil Private (PIN)", price: 78000, originalPrice: 150000, isDefault: false },
    ],
  },
  {
    id: "prod-hbo-max",
    name: "HBO Max / Max Premium",
    slug: "hbo-max",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Nonton House of the Dragon, Harry Potter, DC Universe, dan Warner Bros originals.",
    features: ["Kualitas 4K Dolby Vision", "Original HBO & Warner Bros", "Multi-Audio & Sub Indo", "Garansi Full 30 Hari"],
    icon: "Tv",
    badge: "🐉 House of Dragon",
    badgeColor: "lilac",
    isPopular: true,
    warrantyDays: 30,
    order: 102,
    variants: [
      { id: "v-hbo-1m-1p", productId: "prod-hbo-max", duration: "1 Bulan", accountType: "1 Profil Sharing", price: 22000, originalPrice: 45000, isDefault: true },
      { id: "v-hbo-1m-pr", productId: "prod-hbo-max", duration: "1 Bulan", accountType: "Private Full", price: 65000, originalPrice: 120000, isDefault: false },
      { id: "v-hbo-3m-1p", productId: "prod-hbo-max", duration: "3 Bulan", accountType: "1 Profil Sharing", price: 55000, originalPrice: 110000, isDefault: false },
    ],
  },
  {
    id: "prod-prime-video",
    name: "Prime Video (Amazon)",
    slug: "prime-video",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Nonton The Boys, Rings of Power, Fallout, dan film bioskop Hollywood terbaru.",
    features: ["Kualitas 4K UHD", "Bonus Twitch Prime Gaming", "Sub Indo & Dubbing Lengkap", "Garansi Sesuai Durasi"],
    icon: "Clapperboard",
    badge: "⭐ Hemat 70%",
    badgeColor: "blue",
    isPopular: true,
    warrantyDays: 30,
    order: 103,
    variants: [
      { id: "v-prime-1m-1p", productId: "prod-prime-video", duration: "1 Bulan", accountType: "1 Profil", price: 15000, originalPrice: 35000, isDefault: true },
      { id: "v-prime-1m-pr", productId: "prod-prime-video", duration: "1 Bulan", accountType: "Private", price: 35000, originalPrice: 79000, isDefault: false },
      { id: "v-prime-3m-1p", productId: "prod-prime-video", duration: "3 Bulan", accountType: "1 Profil", price: 38000, originalPrice: 95000, isDefault: false },
    ],
  },
  {
    id: "prod-wetv",
    name: "WeTV VIP",
    slug: "wetv-vip",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Spesialis C-Drama, Drama Romantis, dan Series Indonesia populer seperti Layangan Putus.",
    features: ["Fast Track Episode Baru", "Bebas Iklan & HD 1080p", "Dolby Sound Effects", "Garansi Terjamin"],
    icon: "Video",
    badge: "🌸 Top C-Drama",
    badgeColor: "pink",
    isPopular: true,
    warrantyDays: 30,
    order: 104,
    variants: [
      { id: "v-wetv-1m-sh", productId: "prod-wetv", duration: "1 Bulan", accountType: "Sharing", price: 14000, originalPrice: 35000, isDefault: true },
      { id: "v-wetv-1m-pr", productId: "prod-wetv", duration: "1 Bulan", accountType: "Private", price: 32000, originalPrice: 65000, isDefault: false },
      { id: "v-wetv-3m-sh", productId: "prod-wetv", duration: "3 Bulan", accountType: "Sharing", price: 35000, originalPrice: 90000, isDefault: false },
      { id: "v-wetv-1y-pr", productId: "prod-wetv", duration: "1 Tahun", accountType: "Private", price: 160000, originalPrice: 350000, isDefault: false },
    ],
  },
  {
    id: "prod-vision-plus",
    name: "Vision+ Premium Sports",
    slug: "vision-plus",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Tayangan olahraga terlengkap (Timnas Indonesia, MotoGP, BWF Badminton) & TV Nasional.",
    features: ["Live Match Timnas & BWF", "Live TV Indonesia & Mancanegara", "Kualitas HD Jernih", "Garansi Aktif"],
    icon: "Trophy",
    badge: "⚽ Live Timnas",
    badgeColor: "yellow",
    isPopular: true,
    warrantyDays: 30,
    order: 105,
    variants: [
      { id: "v-vision-1m-sh", productId: "prod-vision-plus", duration: "1 Bulan", accountType: "Sharing", price: 18000, originalPrice: 40000, isDefault: true },
      { id: "v-vision-1m-pr", productId: "prod-vision-plus", duration: "1 Bulan", accountType: "Private", price: 42000, originalPrice: 85000, isDefault: false },
      { id: "v-vision-1y-pr", productId: "prod-vision-plus", duration: "1 Tahun", accountType: "Private", price: 185000, originalPrice: 380000, isDefault: false },
    ],
  },
  {
    id: "prod-disney",
    name: "Disney+ Hotstar",
    slug: "disney-plus",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Koleksi Marvel, Star Wars, Pixar, Disney Princess, dan drama Korea eksklusif.",
    features: ["Marvel Cinematic Universe", "Kualitas Full HD & 4K", "Bisa Smart TV & HP", "Garansi Penuh"],
    icon: "Sparkles",
    badge: "🦸 Marvel & Pixar",
    badgeColor: "blue",
    isPopular: true,
    warrantyDays: 30,
    order: 106,
    variants: [
      { id: "v-disney-1m-1p", productId: "prod-disney", duration: "1 Bulan", accountType: "1 Device Sharing", price: 26000, originalPrice: 65000, isDefault: true },
      { id: "v-disney-1m-pr", productId: "prod-disney", duration: "1 Bulan", accountType: "Private", price: 95000, originalPrice: 150000, isDefault: false },
      { id: "v-disney-3m-1p", productId: "prod-disney", duration: "3 Bulan", accountType: "1 Device Sharing", price: 68000, originalPrice: 170000, isDefault: false },
    ],
  },
  {
    id: "prod-viu",
    name: "Viu Premium",
    slug: "viu-premium",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Surga Drakor dengan subtitle Indonesia tercepat tayang hanya hitungan jam setelah Korea.",
    features: ["Sub Indo Paling Cepat", "Bebas Iklan & Download Offline", "Kualitas Full HD 1080p", "Garansi Anti-Hold"],
    icon: "Heart",
    badge: "🇰🇷 Rajanya Drakor",
    badgeColor: "pink",
    isPopular: true,
    warrantyDays: 30,
    order: 107,
    variants: [
      { id: "v-viu-1m-pr", productId: "prod-viu", duration: "1 Bulan", accountType: "Private Akun", price: 12000, originalPrice: 39000, isDefault: true },
      { id: "v-viu-3m-pr", productId: "prod-viu", duration: "3 Bulan", accountType: "Private Akun", price: 25000, originalPrice: 85000, isDefault: false },
      { id: "v-viu-6m-pr", productId: "prod-viu", duration: "6 Bulan", accountType: "Private Akun", price: 42000, originalPrice: 140000, isDefault: false },
      { id: "v-viu-1y-pr", productId: "prod-viu", duration: "1 Tahun", accountType: "Private Akun", price: 65000, originalPrice: 220000, isDefault: false },
    ],
  },
  {
    id: "prod-bstation",
    name: "Bstation / Bilibili Premium",
    slug: "bstation-premium",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Platform streaming anime resmi terbesar dengan resolusi 1080p/4K 60FPS dan audio jernih.",
    features: ["Anime Terlengkap & Terupdate", "Resolusi 4K & 1080p 60fps", "Download Anime Offline", "Garansi Full"],
    icon: "Tv2",
    badge: "⚡ Surganya Anime",
    badgeColor: "lilac",
    isPopular: true,
    warrantyDays: 30,
    order: 108,
    variants: [
      { id: "v-bstation-1m-pr", productId: "prod-bstation", duration: "1 Bulan", accountType: "Private Akun", price: 14000, originalPrice: 35000, isDefault: true },
      { id: "v-bstation-3m-pr", productId: "prod-bstation", duration: "3 Bulan", accountType: "Private Akun", price: 32000, originalPrice: 85000, isDefault: false },
      { id: "v-bstation-1y-pr", productId: "prod-bstation", duration: "1 Tahun", accountType: "Private Akun", price: 85000, originalPrice: 230000, isDefault: false },
    ],
  },
  {
    id: "prod-youtube",
    name: "YouTube Premium + YT Music",
    slug: "youtube-premium",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Nonton YouTube tanpa jeda iklan, bisa putar di latar belakang, dan gratis YouTube Music.",
    features: ["No Ads / Bebas Iklan", "Background Play / Lock Screen", "Termasuk YouTube Music", "Via Invite Family / Individual"],
    icon: "PlayCircle",
    badge: "🎵 No Ads + Music",
    badgeColor: "pink",
    isPopular: true,
    warrantyDays: 30,
    order: 109,
    variants: [
      { id: "v-yt-1m-inv", productId: "prod-youtube", duration: "1 Bulan", accountType: "Invite Email Sendiri", price: 10000, originalPrice: 25000, isDefault: true },
      { id: "v-yt-3m-inv", productId: "prod-youtube", duration: "3 Bulan", accountType: "Invite Email Sendiri", price: 25000, originalPrice: 65000, isDefault: false },
      { id: "v-yt-6m-inv", productId: "prod-youtube", duration: "6 Bulan", accountType: "Invite Email Sendiri", price: 48000, originalPrice: 120000, isDefault: false },
      { id: "v-yt-1y-inv", productId: "prod-youtube", duration: "1 Tahun", accountType: "Invite Email Sendiri", price: 85000, originalPrice: 220000, isDefault: false },
    ],
  },
  {
    id: "prod-dramabox",
    name: "Dramabox VIP Unlimited",
    slug: "dramabox-vip",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Aplikasi mini drama vertikal viral tentang CEO, balas dendam, dan romansa kilat.",
    features: ["Unlimited Coins & Episode", "Semua Series Terbuka", "Subtitle Indonesia", "Garansi Aktif"],
    icon: "Smartphone",
    badge: "📱 Viral TikTok",
    badgeColor: "yellow",
    isPopular: true,
    warrantyDays: 30,
    order: 110,
    variants: [
      { id: "v-dbox-1m-pr", productId: "prod-dramabox", duration: "1 Bulan", accountType: "Private", price: 28000, originalPrice: 70000, isDefault: true },
      { id: "v-dbox-3m-pr", productId: "prod-dramabox", duration: "3 Bulan", accountType: "Private", price: 65000, originalPrice: 160000, isDefault: false },
    ],
  },
  {
    id: "prod-crunchyroll",
    name: "Crunchyroll Mega Fan",
    slug: "crunchyroll-mega-fan",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Simulcast anime langsung 1 jam setelah tayang di Jepang, bebas iklan & multi device.",
    features: ["Simulcast 1 Jam Pasca Jepang", "Mega Fan 4 Devices", "Nonton Offline Download", "Garansi Full"],
    icon: "Tv",
    badge: "🍙 Mega Fan",
    badgeColor: "yellow",
    isPopular: false,
    warrantyDays: 30,
    order: 111,
    variants: [
      { id: "v-crunch-1m-sh", productId: "prod-crunchyroll", duration: "1 Bulan", accountType: "Sharing", price: 15000, originalPrice: 40000, isDefault: true },
      { id: "v-crunch-1m-pr", productId: "prod-crunchyroll", duration: "1 Bulan", accountType: "Private", price: 38000, originalPrice: 85000, isDefault: false },
      { id: "v-crunch-1y-pr", productId: "prod-crunchyroll", duration: "1 Tahun", accountType: "Private", price: 160000, originalPrice: 390000, isDefault: false },
    ],
  },
  {
    id: "prod-reelshort",
    name: "Reelshort VIP",
    slug: "reelshort-vip",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Mini series pendek adiktif dengan plot twist seru tanpa perlu top-up koin mahal.",
    features: ["Unlock All Mini Series", "Bebas Iklan", "Episode Full HD", "Garansi Terpercaya"],
    icon: "Video",
    badge: "🎬 Mini Series",
    badgeColor: "pink",
    isPopular: true,
    warrantyDays: 30,
    order: 112,
    variants: [
      { id: "v-reel-1m-pr", productId: "prod-reelshort", duration: "1 Bulan", accountType: "Private", price: 30000, originalPrice: 75000, isDefault: true },
      { id: "v-reel-3m-pr", productId: "prod-reelshort", duration: "3 Bulan", accountType: "Private", price: 70000, originalPrice: 180000, isDefault: false },
    ],
  },
  {
    id: "prod-youku",
    name: "Youku VIP",
    slug: "youku-vip",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Koleksi drama kolosal wuxia, xianxia, dan variety show Mandarin terlengkap.",
    features: ["Akses Semua Drama VIP", "HD 1080p & Sub Indo", "Akses Awal Episode Baru", "Garansi Full"],
    icon: "Tv",
    badge: "🏮 Kolosal & Xianxia",
    badgeColor: "blue",
    isPopular: false,
    warrantyDays: 30,
    order: 113,
    variants: [
      { id: "v-youku-1m-pr", productId: "prod-youku", duration: "1 Bulan", accountType: "Private", price: 18000, originalPrice: 45000, isDefault: true },
      { id: "v-youku-3m-pr", productId: "prod-youku", duration: "3 Bulan", accountType: "Private", price: 45000, originalPrice: 110000, isDefault: false },
    ],
  },
  {
    id: "prod-melolo",
    name: "Melolo VIP",
    slug: "melolo-vip",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Streaming drama romantis pendek dan novel visual interaktif favorit.",
    features: ["Semua Episode Unlocked", "Tanpa Jeda Iklan", "Kualitas Gambar Bersih", "Garansi Penuh"],
    icon: "HeartHandshake",
    badge: "💕 Drama Romantis",
    badgeColor: "pink",
    isPopular: false,
    warrantyDays: 30,
    order: 114,
    variants: [
      { id: "v-melolo-1m", productId: "prod-melolo", duration: "1 Bulan", accountType: "Private", price: 25000, originalPrice: 60000, isDefault: true },
      { id: "v-melolo-3m", productId: "prod-melolo", duration: "3 Bulan", accountType: "Private", price: 60000, originalPrice: 150000, isDefault: false },
    ],
  },
  {
    id: "prod-drakor-id",
    name: "Drakor ID VIP",
    slug: "drakor-id",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Aplikasi ringan khusus pecinta drama Korea dan variety show dengan server kencang.",
    features: ["Server Anti-Buffering", "Download Batch Cepat", "Tanpa Iklan Banner", "Garansi Replace"],
    icon: "Film",
    badge: "⚡ Server Kencang",
    badgeColor: "mint",
    isPopular: false,
    warrantyDays: 30,
    order: 115,
    variants: [
      { id: "v-drakorid-1m", productId: "prod-drakor-id", duration: "1 Bulan", accountType: "VIP No Ads", price: 15000, originalPrice: 35000, isDefault: true },
      { id: "v-drakorid-3m", productId: "prod-drakor-id", duration: "3 Bulan", accountType: "VIP No Ads", price: 35000, originalPrice: 85000, isDefault: false },
    ],
  },
  {
    id: "prod-iqiyi",
    name: "iQIYI VIP Standard / Diamond",
    slug: "iqiyi-vip",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Nonton C-Drama romantis, Anime, dan K-Drama dengan fitur Dolby Audio & resolusi 4K.",
    features: ["Dolby Audio & 4K Ultra HD", "Akses Awal Episode VIP", "Bebas Iklan", "Garansi Penuh 30 Hari"],
    icon: "Play",
    badge: "🌟 K-Drama & C-Drama",
    badgeColor: "mint",
    isPopular: true,
    warrantyDays: 30,
    order: 116,
    variants: [
      { id: "v-iq-1m-sh", productId: "prod-iqiyi", duration: "1 Bulan", accountType: "Standard Sharing", price: 15000, originalPrice: 39000, isDefault: true },
      { id: "v-iq-1m-pr", productId: "prod-iqiyi", duration: "1 Bulan", accountType: "Standard Private", price: 35000, originalPrice: 79000, isDefault: false },
      { id: "v-iq-1y-pr", productId: "prod-iqiyi", duration: "1 Tahun", accountType: "Standard Private", price: 175000, originalPrice: 399000, isDefault: false },
    ],
  },
  {
    id: "prod-vidio",
    name: "Vidio Platinum & Diamond",
    slug: "vidio-premier",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Nonton Premier League (Liga Inggris), BRI Liga 1, UCL, NBA, dan Vidio Original Series.",
    features: ["Liga Inggris & BRI Liga 1", "Vidio Original Series", "Live TV Nasional & Olahraga", "Garansi Aktif"],
    icon: "Tv",
    badge: "🏆 Liga Inggris & TV",
    badgeColor: "pink",
    isPopular: true,
    warrantyDays: 30,
    order: 117,
    variants: [
      { id: "v-vidio-plat-1m", productId: "prod-vidio", duration: "1 Bulan", accountType: "Platinum (Film & Series)", price: 18000, originalPrice: 39000, isDefault: false },
      { id: "v-vidio-diam-1m", productId: "prod-vidio", duration: "1 Bulan", accountType: "Diamond (All EPL + All)", price: 45000, originalPrice: 99000, isDefault: true },
      { id: "v-vidio-diam-1y", productId: "prod-vidio", duration: "1 Tahun", accountType: "Diamond Private", price: 390000, originalPrice: 850000, isDefault: false },
    ],
  },
  {
    id: "prod-gagaoolala",
    name: "GagaOOLala VIP",
    slug: "gagaoolala-vip",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Platform streaming film dan serial Asia bertema romansa LGBTQ+, BL & GL terlengkap.",
    features: ["Koleksi BL / GL Terlengkap", "Sub Indo & High Definition", "Bebas Iklan", "Garansi Terjamin"],
    icon: "Rainbow",
    badge: "🌈 Asian BL & Cinema",
    badgeColor: "lilac",
    isPopular: false,
    warrantyDays: 30,
    order: 118,
    variants: [
      { id: "v-gaga-1m-sh", productId: "prod-gagaoolala", duration: "1 Bulan", accountType: "Sharing", price: 25000, originalPrice: 65000, isDefault: true },
      { id: "v-gaga-1m-pr", productId: "prod-gagaoolala", duration: "1 Bulan", accountType: "Private", price: 60000, originalPrice: 140000, isDefault: false },
    ],
  },
  {
    id: "prod-shortmax",
    name: "Shortmax VIP Unlimited",
    slug: "shortmax-vip",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Mini serial pendek dengan episode instan tanpa limit nonton sepuasnya.",
    features: ["Semua Episode Unlocked", "HD Resolution", "Tanpa Iklan", "Garansi Replace"],
    icon: "Smartphone",
    badge: "📱 Mini Drama",
    badgeColor: "yellow",
    isPopular: false,
    warrantyDays: 30,
    order: 119,
    variants: [
      { id: "v-shortmax-1m", productId: "prod-shortmax", duration: "1 Bulan", accountType: "Private", price: 28000, originalPrice: 70000, isDefault: true },
    ],
  },
  {
    id: "prod-catchplay",
    name: "Catchplay+ Movie Lovers",
    slug: "catchplay-plus",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Nonton film bioskop Hollywood terbaru dan serial blockbuster dengan kualitas HD.",
    features: ["Film Bioskop Box Office", "Single Rental Voucher", "Sub Indo & Audio Dolby", "Garansi Full"],
    icon: "Film",
    badge: "🍿 Bioskop di Rumah",
    badgeColor: "blue",
    isPopular: false,
    warrantyDays: 30,
    order: 120,
    variants: [
      { id: "v-catchplay-1m-pr", productId: "prod-catchplay", duration: "1 Bulan", accountType: "Private", price: 22000, originalPrice: 55000, isDefault: true },
    ],
  },
  {
    id: "prod-netshort",
    name: "Netshort VIP",
    slug: "netshort-vip",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Short drama trending dengan jalan cerita seru dan bikin ketagihan.",
    features: ["Unlocked Semua Cerita", "Sub Indo Jelas", "No Ads", "Garansi Aktif"],
    icon: "Video",
    badge: "🔥 Trending Drama",
    badgeColor: "pink",
    isPopular: false,
    warrantyDays: 30,
    order: 121,
    variants: [
      { id: "v-netshort-1m", productId: "prod-netshort", duration: "1 Bulan", accountType: "Private", price: 28000, originalPrice: 65000, isDefault: true },
    ],
  },
  {
    id: "prod-viki",
    name: "Viki Pass Standard / Plus",
    slug: "viki-pass",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Koleksi drama Asia terlengkap dengan subtitle multi-bahasa dari komunitas terpercaya.",
    features: ["Akses Drama Viki Eksklusif", "Bebas Iklan & HD 1080p", "Subtitle Terjemahan Lengkap", "Garansi Anti-Hold"],
    icon: "Tv",
    badge: "🌏 Asian Drama Pass",
    badgeColor: "lilac",
    isPopular: true,
    warrantyDays: 30,
    order: 122,
    variants: [
      { id: "v-viki-1m-sh", productId: "prod-viki", duration: "1 Bulan", accountType: "Sharing", price: 22000, originalPrice: 50000, isDefault: true },
      { id: "v-viki-1m-pr", productId: "prod-viki", duration: "1 Bulan", accountType: "Private", price: 55000, originalPrice: 120000, isDefault: false },
      { id: "v-viki-1y-pr", productId: "prod-viki", duration: "1 Tahun", accountType: "Private", price: 260000, originalPrice: 600000, isDefault: false },
    ],
  },
  {
    id: "prod-dramabite",
    name: "Dramabite VIP",
    slug: "dramabite-vip",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Episode singkat padat romansa manis dan cerita konglomerat menegangkan.",
    features: ["Fast Track All Episode", "Full HD", "Bebas Iklan", "Garansi Penuh"],
    icon: "Heart",
    badge: "🧁 Drama Manis",
    badgeColor: "pink",
    isPopular: false,
    warrantyDays: 30,
    order: 123,
    variants: [
      { id: "v-dramabite-1m", productId: "prod-dramabite", duration: "1 Bulan", accountType: "Private", price: 26000, originalPrice: 65000, isDefault: true },
    ],
  },
  {
    id: "prod-loklok",
    name: "Loklok VIP",
    slug: "loklok-vip",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Streaming anime, film, dan drama multi-genre dengan fitur download dan kualitas HD.",
    features: ["VIP High Speed Server", "Download Tanpa Batas", "Tanpa Iklan", "Garansi Aktif"],
    icon: "PlaySquare",
    badge: "🎬 All in One",
    badgeColor: "yellow",
    isPopular: false,
    warrantyDays: 30,
    order: 124,
    variants: [
      { id: "v-loklok-1m", productId: "prod-loklok", duration: "1 Bulan", accountType: "Private", price: 18000, originalPrice: 40000, isDefault: true },
      { id: "v-loklok-3m", productId: "prod-loklok", duration: "3 Bulan", accountType: "Private", price: 45000, originalPrice: 100000, isDefault: false },
    ],
  },
  {
    id: "prod-bili-tv",
    name: "Bili-TV VIP",
    slug: "bili-tv",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Aplikasi Bstation versi Smart TV untuk menikmati anime & drama di layar lebar.",
    features: ["Kualitas 4K Smart TV", "Audio Surround", "Sync Watch History", "Garansi Penuh"],
    icon: "Tv",
    badge: "📺 Smart TV Mode",
    badgeColor: "blue",
    isPopular: false,
    warrantyDays: 30,
    order: 125,
    variants: [
      { id: "v-bilitv-1m", productId: "prod-bili-tv", duration: "1 Bulan", accountType: "Private Device", price: 20000, originalPrice: 45000, isDefault: true },
    ],
  },
  {
    id: "prod-web-dracin",
    name: "Web Dracin VIP",
    slug: "web-dracin",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Akses premium portal drama China eksklusif dengan raw sub tercepat dan resolusi tajam.",
    features: ["Akses Episode Raw & Sub", "Server VIP Super Cepat", "Bebas Iklan", "Garansi Aktif"],
    icon: "Globe",
    badge: "🏮 Portal Dracin",
    badgeColor: "yellow",
    isPopular: false,
    warrantyDays: 30,
    order: 126,
    variants: [
      { id: "v-dracin-1m", productId: "prod-web-dracin", duration: "1 Bulan", accountType: "VIP Pass", price: 16000, originalPrice: 35000, isDefault: true },
    ],
  },
  {
    id: "prod-stremio",
    name: "Stremio Real-Debrid Multi-Source",
    slug: "stremio-rd",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Setup Real-Debrid premium untuk Stremio, streaming film 4K tanpa buffering dari jutaan sumber.",
    features: ["High Speed 4K Torrents Cache", "Semua Film & Serial Dunia", "Support Android TV, PC, HP", "Full Setup Guide"],
    icon: "Compass",
    badge: "🚀 4K Zero Buffering",
    badgeColor: "lilac",
    isPopular: true,
    warrantyDays: 30,
    order: 127,
    variants: [
      { id: "v-stremio-1m", productId: "prod-stremio", duration: "1 Bulan", accountType: "Real-Debrid Key", price: 35000, originalPrice: 75000, isDefault: true },
      { id: "v-stremio-3m", productId: "prod-stremio", duration: "3 Bulan", accountType: "Real-Debrid Key", price: 85000, originalPrice: 190000, isDefault: false },
      { id: "v-stremio-6m", productId: "prod-stremio", duration: "6 Bulan", accountType: "Real-Debrid Key", price: 155000, originalPrice: 340000, isDefault: false },
    ],
  },
  {
    id: "prod-dramawave",
    name: "Dramawave VIP",
    slug: "dramawave-vip",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Gelombang mini series global terbaru dengan terjemahan bahasa Indonesia super rapi.",
    features: ["Global Mini Series", "Unlocked Semua Chapter", "No Ads", "Garansi Penuh"],
    icon: "Waves",
    badge: "🌊 Mini Wave",
    badgeColor: "blue",
    isPopular: false,
    warrantyDays: 30,
    order: 128,
    variants: [
      { id: "v-dwave-1m", productId: "prod-dramawave", duration: "1 Bulan", accountType: "Private", price: 25000, originalPrice: 60000, isDefault: true },
    ],
  },
  {
    id: "prod-idrama",
    name: "iDrama VIP",
    slug: "idrama-vip",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Streaming drama Asia bebas watermark dengan subtitle jernih dan loading instan.",
    features: ["Bebas Watermark", "Subtitle Jernih", "Hemat Kuota", "Garansi Sesuai Durasi"],
    icon: "Video",
    badge: "✨ Jernih & Ringan",
    badgeColor: "mint",
    isPopular: false,
    warrantyDays: 30,
    order: 129,
    variants: [
      { id: "v-idrama-1m", productId: "prod-idrama", duration: "1 Bulan", accountType: "Private", price: 20000, originalPrice: 45000, isDefault: true },
    ],
  },
  {
    id: "prod-stardust",
    name: "Stardust TV VIP",
    slug: "stardust-vip",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Hiburan visual premium dan drama romansa bintang dengan kualitas tinggi.",
    features: ["Semua Konten VIP", "Kualitas Gambar Tajam", "Full Garansi", "Proses Cepat"],
    icon: "Star",
    badge: "⭐ Stardust HD",
    badgeColor: "yellow",
    isPopular: false,
    warrantyDays: 30,
    order: 130,
    variants: [
      { id: "v-stardust-1m", productId: "prod-stardust", duration: "1 Bulan", accountType: "Private", price: 24000, originalPrice: 55000, isDefault: true },
    ],
  },
  {
    id: "prod-storyreel",
    name: "Storyreel VIP",
    slug: "storyreel-vip",
    categoryId: "cat-streaming",
    categorySlug: "streaming-apps",
    description: "Kumpulan cerita pendek dan reel drama seru yang bikin betah maraton nonton.",
    features: ["Reels Drama Tanpa Koin", "Full Episode Unlocked", "Kualitas HD", "Garansi Aktif"],
    icon: "Film",
    badge: "🎬 Maraton Drama",
    badgeColor: "pink",
    isPopular: false,
    warrantyDays: 30,
    order: 131,
    variants: [
      { id: "v-storyreel-1m", productId: "prod-storyreel", duration: "1 Bulan", accountType: "Private", price: 27000, originalPrice: 65000, isDefault: true },
    ],
  },
];
